### ISSUE TITLE
How to compare bin file of lol

### ISSUE THREAD

**Issue by darkderosa** [Pupix/lol-bin-parser#1]
Hi pupix,
    I'm new in Github and I don't know the right way to send msg to you on Github. So I write the question here.
    For some reason I need to compare the bin files, for example "Fizz.bin" in 6.1 patch and 6.2 patch. I have to figure out what exactlly changed in bin file.
    But I've no idea the structure of the bin file and then find your lol-bin-parser. I've tried to use this program to parse bin file of 6.3 patch, but get the text all like " '606053171':  [ [Object], …". So I still can't get what is changed in bin file.
    I will be very appreciate if you can give me some suggestions about this question. Thank you.

**Comment by Pupix** [comment]
Hello and welcome to GitHub!

To check the differences between the two resulting objects you should use a diff library like [this](https://github.com/flitbit/diff) or [this](https://github.com/cosmicanant/recursive-diff). They will output only the different bits of information, however you still have to understand what the hash key means as they are not yet mapped to humanized strings.

Cheers.

**Comment by darkderosa** [comment]
Thank you for the quick response Pupix.
I'll try that diff module. So the numbers like  '606053171' is the hash key you mentioned? I've got a map of strings for hash keys, but not completed, still some keys cannot be decoded. Let me try to use the old map even though. 
Thank you very much.

**Comment by Pupix** [comment]
Yes, the left hand numbers such as "606053171" are the hash keys used by the game to identify the values. Inibin files used to have unique hashes, but these new .bin files have duplicates meaning there's a whole new hashing algorithm.

**Comment by darkderosa** [comment]
Bad news, more tough work are waiting for me....Thank you for your nice suggestion.
