### ISSUE TITLE
Run to test this

### ISSUE THREAD

**Issue by supernghia89** [Pupix/lol-bin-parser#2]
Hello

I'm new in GitHub. I found your projects by googe. Them looking very awsome

But i dont know how to run this lol-bin-parser to test it

I downloaded the NodeJS to PC but i don't known what next i to do

Plz

**Comment by Pupix** [comment]
Hello!

What exactly do you mean you don't know what to do? What are you trying to use the parser for, do you have a snippet of your code? Have you never used NodeJS before?

Cheers.

**Comment by supernghia89** [comment]
Hi Pupix !

Thank you for reply me.

This is the first time I used NodeJS. I have read the Readme.md file and use the command "npm install lol-inibin-parser" on the "Node.js command prompt" but the following error appears:

> C:\Users\Phoenix>npm install lol-bin-parser
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "lol-bin-parser"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code EINVAL
> npm ERR! errno EINVAL
> npm ERR! syscall spawn
> 
> npm ERR! spawn EINVAL
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Phoenix\npm-debug.log

I try with the command "npm install lol-inibin-parser" does not appear similar error with "lol-inibin-parser"

My code is a sample code in readme.md file

```
var BinParser = require('lol-bin-parser'),
    bin = new BinParser();

    // Read the package.json file
    bin.read('Fizz.bin', function (err, data) {
        console.log(data);
    });
```

**Comment by supernghia89** [comment]
Please help

> F:\WORK>node test.js
> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'html-json-forms'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at F:\WORK\SVN\NGHIATD\LOL Research\lol-bin-parser\node_modules\expandjs\lib\dom\formData.js:15:26
>     at Object.<anonymous> (F:\WORK\lol-bin-parser\node_modules\expandjs\lib\dom\formData.js:32:2)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)

test.js

```
var BinParser = require('./lol-bin-parser'),
    bin = new BinParser();

    // Read the package.json file
    bin.read('./Fizz.bin', function (err, data) {
        console.log(data);
    });
```

**Comment by Pupix** [comment]
You need to install the modules before you can use them.

[Here](http://www.tutorialspoint.com/nodejs/nodejs_introduction.htm)'s a generic nodeJS/npm tutorial to get you started.
