### ISSUE TITLE
unknown .bin version

### ISSUE THREAD

**Issue by daQiuQiu** [Pupix/lol-bin-parser#3]
I have tried your parser for the .bin file in chunks and keyframe, it gives a error unknown .bin version,
any idea?
is it not using for .bin file in chunks and keyframe?

**Comment by Pupix** [comment]
Don't know what chunks or keyframes you are talking about. Can you upload the file?
Also the error is pretty clear, the version of the file you are using is not yet supported.

**Comment by daQiuQiu** [comment]
[bin.zip](https://github.com/Pupix/lol-bin-parser/files/599114/bin.zip)
File uplaoded.
So it can use for what kind of  bin file?

**Comment by Pupix** [comment]
It was built to be used with `,bin` files that are packed inside `.wad` or present inside champions folder. Don't know what those files you send me are, they don't follow the structure expected for this parser.

**Comment by daQiuQiu** [comment]
So, this parser is not for replay files? whats the output data then?

Im new to study lol data...
thanks for your time~

**Comment by Pupix** [comment]
Not as far as I am aware. `.bin` is a generic extension and can be used for any file.

Haven't had a look at the replays format yet, will reopen this let you know if I decide to implement them.
